# Generated by Django 4.2.3 on 2023-07-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niwera_rpg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Personagem', 'verbose_name_plural': 'Personagens'},
        ),
        migrations.AlterModelOptions(
            name='characterstory',
            options={'verbose_name': 'Personagem na História', 'verbose_name_plural': 'Personagens na História'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'História', 'verbose_name_plural': 'Histórias'},
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='xp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
