# Generated by Django 4.2.3 on 2023-07-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niwera_rpg', '0002_alter_character_options_alter_characterstory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
    ]
